### ISSUE TITLE
Don't rename your files

### ISSUE THREAD

**Issue by KewTeacher** [ForestMilles/chapter_5#1]
Keep the file names the same. I know this may seem overly detailed, but quite often it's not only the coding that counts, it's where it happens, what the file name is and where that file is placed. Right now all of our programs have been contained in one file. When we get into more complex programs, they will have many files. 

You can just copy the code from your fixed files to the original ones, then delete the fixed files for clarity.

Let me know when you've done this.

**Comment by ForestMilles** [comment]
I took what I had in 1,2, and 6.py and copied it as you said into the corresponding one, two, and six.py. then i deleted the 1,2, and 6.py as asked.
